PROCESSED_DATA_PATH = "../data"

COMBINED_CSV_PATH = f"{PROCESSED_DATA_PATH}/combined.csv"
COMBINED_NPY_PATH = f"{PROCESSED_DATA_PATH}/combined.npy"

TEXT_FIELDS = ["bio_description", "content"]

ENCODER_MODEL_NAME = "jinaai/jina-clip-v2"
ENCODER_MAX_LENGTH = 256
ENCODER_BATCH_SIZE = 512

TRAIN_BATCH_SIZE = 512
TRAIN_D_MODEL = 64
TRAIN_EPOCHS = 100
TRAIN_SIZE = 0.7
VAL_SIZE = 0.15
TRAIN_PATIENCE = 15
TRAIN_NUM_WORKERS = 4
TRAIN_PIN_MEMORY = True
TRAIN_PREFETCH_FACTOR = 2
TRAIN_PERSISTENT_WORKERS = True

FTRL_ALPHA = 0.01
FTRL_BETA = 1.0
FTRL_L1 = 1e-2
FTRL_L2 = 1e-3
ADAM_LR = 1e-4
ADAM_WEIGHT_DECAY = 1e-4

EMAIL_SENDER = ""
EMAIL_PASS = ''
EMAIL_RECEIVER = ""